spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: chenyang
    password: 888888

database:
  address: 127.0.0.1
  port: 5432
  user: postgres
  password: postgres
  dbname: water_flow_dev